<script>
  import * as Icon from '$lib';
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return '#' + n.slice(0, 6);
  };
</script>

<div class="flex flex-wrap justify-between bg-gray-700">
  <Icon.$Pac size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.A0Xbtc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.A2Give size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Aave size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Abt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Act size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Actn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ada size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Add size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Adx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ae size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Aeon size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Aeur size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Agi size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Agrs size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Aion size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Algo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Amb size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Amp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ampl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ankr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ant size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Apex size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Appc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ardr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Arg size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ark size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Arn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Arnx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ary size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ast size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Atm size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Atom size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Audr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Auto size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Aywa size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bab size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bal size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Band size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bat size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bay size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bcbc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bcc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bcd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bch size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bcio size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bcn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bco size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bcpt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bdl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Beam size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bela size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bix size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Blcn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Blk size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Block size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Blz size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bnb size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bnt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bnty size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Booty size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bos size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bpt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bq size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Brd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bsd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bsv size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btcd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btch size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btcp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btcz size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btdx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btg size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btm size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bts size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Btx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Burst size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Bze size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Call size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cdn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cdt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cenz size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Chain size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Chat size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Chips size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Chsb size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cix size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Clam size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cloak size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cmm size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cmt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cnd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cnx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cny size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cob size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Colx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Comp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Coqui size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cred size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Crpt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Crv size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Crw size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cs size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ctr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ctxc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Cvc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.D size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dai size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dash size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dat size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Data size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dbc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dcn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dcr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Deez size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dent size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dew size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dgb size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dgd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dlt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dnt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dock size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Doge size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dot size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Drgn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Drop size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dta size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dth size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Dtr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ebst size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Eca size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Edg size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Edo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Edoge size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ela size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Elec size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Elf size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Elix size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ella size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Emb size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Emc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Emc2 size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Eng size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Enj size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Entrp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Eon size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Eop size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Eos size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Eqli size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Equa size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Etc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Eth size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ethos size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Etn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Etp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Eur size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Evx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Exmo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Exp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Fair size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Fct size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Fil size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Fjc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Fldc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Flo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Flux size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Fsn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ftc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Fuel size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Fun size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Game size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gas size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gbp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gbx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gbyte size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Generic size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gin size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Glxt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gmr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gno size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gnt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gold size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Grc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Grin size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Grs size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Grt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gsc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gto size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gup size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gusd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gvt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gxs size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Gzr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Hight size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Hns size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Hodl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Hot size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Hpb size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Hsr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ht size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Html size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Huc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Husd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Hush size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Icn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Icp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Icx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ignis size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ilk size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ink size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ins size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ion size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Iop size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Iost size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Iotx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Iq size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Itc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Jnt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Jpy size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Kcs size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Kin size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Klown size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Kmd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Knc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Krb size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ksm size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Lbc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Lend size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Leo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Link size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Lkk size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Loom size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Lpt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Lrc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Lsk size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ltc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Lun size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Maid size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mana size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Matic size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Max size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mcap size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mco size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mda size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mds size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Med size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Meetone size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mft size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Miota size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mith size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mkr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mln size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mnx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mnz size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Moac size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mod size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mona size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Msr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mth size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mtl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Music size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Mzc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nano size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nas size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nav size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ncash size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ndz size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nebl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Neo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Neos size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Neu size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nexo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ngc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nio size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nkn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nlc2 size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nlg size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nmc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nmr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Npxs size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ntbc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nuls size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nxs size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Nxt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Oax size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ok size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Omg size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Omni size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.One size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ong size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ont size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Oot size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ost size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ox size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Oxt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Part size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pasc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pasl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pax size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Paxg size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pay size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Payx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pink size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pirl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pivx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Plr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Poa size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Poe size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Polis size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Poly size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pot size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Powr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ppc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ppp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ppt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pre size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Prl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pungo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Pura size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Qash size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Qiwi size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Qlc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Qrl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Qsp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Qtum size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.R size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rads size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rap size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rcn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rdd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rdn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ren size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rep size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Repv2 size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Req size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rhoc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ric size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rise size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rlc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rpx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rub size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Rvn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ryo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Safe size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Safemoon size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sai size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Salt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.San size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sand size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sbd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sberbank size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Shift size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sib size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sin size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Skl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sky size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Slr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sls size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Smart size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sngls size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Snm size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Snt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Snx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Soc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sol size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Spacehbit size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Spank size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sphtx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Srn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Stak size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Start size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Steem size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Storj size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Storm size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Stox size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Stq size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Strat size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Stx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sub size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sumo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sushi size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Sys size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Taas size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tau size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tbx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tel size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ten size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tern size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tgch size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Theta size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tix size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tkn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tks size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tnb size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tnc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tnt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tomo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tpay size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Trig size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Trtl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Trx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tusd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Tzc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Ubq size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Uma size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Uni size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Unity size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Usd size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Usdc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Usdt size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Utk size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Veri size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Vet size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Via size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Vib size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Vibe size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Vivo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Vrc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Vrsc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Vtc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Vtho size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Wabi size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Wan size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Waves size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Wax size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Wbtc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Wgr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Wicc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Wings size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Wpr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Wtc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.X size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xas size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xbc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xbp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xby size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xcp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xdn size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xem size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xin size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xlm size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xmcc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xmg size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xmo size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xmr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xmy size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xpa size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xpm size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xpr size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xrp size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xsg size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xtz size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xuc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xvc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xvg size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Xzc size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Yfi size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Yoyow size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Zcl size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Zec size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Zel size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Zen size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Zest size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Zil size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Zilla size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
  <Icon.Zrx size="40" class="m-0.5" color={random_hex_color_code()} variation="white" />
</div>

<svelte:head>
  <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>
</svelte:head>

