<script>
  import * as Icon from '$lib';
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return '#' + n.slice(0, 6);
  };
</script>

<Icon.$Pac size="40" color={random_hex_color_code()} variation="black" />
<Icon.A0Xbtc size="40" color={random_hex_color_code()} variation="black" />
<Icon.A1Inch size="40" color={random_hex_color_code()} variation="black" />
<Icon.A2Give size="40" color={random_hex_color_code()} variation="black" />
<Icon.Aave size="40" color={random_hex_color_code()} variation="black" />
<Icon.Abt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Act size="40" color={random_hex_color_code()} variation="black" />
<Icon.Actn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ada size="40" color={random_hex_color_code()} variation="black" />
<Icon.Add size="40" color={random_hex_color_code()} variation="black" />
<Icon.Adx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ae size="40" color={random_hex_color_code()} variation="black" />
<Icon.Aeon size="40" color={random_hex_color_code()} variation="black" />
<Icon.Aeur size="40" color={random_hex_color_code()} variation="black" />
<Icon.Agi size="40" color={random_hex_color_code()} variation="black" />
<Icon.Agrs size="40" color={random_hex_color_code()} variation="black" />
<Icon.Aion size="40" color={random_hex_color_code()} variation="black" />
<Icon.Algo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Amb size="40" color={random_hex_color_code()} variation="black" />
<Icon.Amp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ampl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ankr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ant size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ape size="40" color={random_hex_color_code()} variation="black" />
<Icon.Apex size="40" color={random_hex_color_code()} variation="black" />
<Icon.Appc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ardr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Arg size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ark size="40" color={random_hex_color_code()} variation="black" />
<Icon.Arn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Arnx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ary size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ast size="40" color={random_hex_color_code()} variation="black" />
<Icon.Atlas size="40" color={random_hex_color_code()} variation="black" />
<Icon.Atm size="40" color={random_hex_color_code()} variation="black" />
<Icon.Atom size="40" color={random_hex_color_code()} variation="black" />
<Icon.Audr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Aury size="40" color={random_hex_color_code()} variation="black" />
<Icon.Auto size="40" color={random_hex_color_code()} variation="black" />
<Icon.Avax size="40" color={random_hex_color_code()} variation="black" />
<Icon.Aywa size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bab size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bal size="40" color={random_hex_color_code()} variation="black" />
<Icon.Band size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bat size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bay size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bcbc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bcc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bcd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bch size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bcio size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bcn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bco size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bcpt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bdl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Beam size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bela size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bix size="40" color={random_hex_color_code()} variation="black" />
<Icon.Blcn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Blk size="40" color={random_hex_color_code()} variation="black" />
<Icon.Block size="40" color={random_hex_color_code()} variation="black" />
<Icon.Blz size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bnb size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bnt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bnty size="40" color={random_hex_color_code()} variation="black" />
<Icon.Booty size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bos size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bpt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bq size="40" color={random_hex_color_code()} variation="black" />
<Icon.Brd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bsd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bsv size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btcd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btch size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btcp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btcz size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btdx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btg size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btm size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bts size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Btx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Burst size="40" color={random_hex_color_code()} variation="black" />
<Icon.Bze size="40" color={random_hex_color_code()} variation="black" />
<Icon.Call size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cdn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cdt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cenz size="40" color={random_hex_color_code()} variation="black" />
<Icon.Chain size="40" color={random_hex_color_code()} variation="black" />
<Icon.Chat size="40" color={random_hex_color_code()} variation="black" />
<Icon.Chips size="40" color={random_hex_color_code()} variation="black" />
<Icon.Chsb size="40" color={random_hex_color_code()} variation="black" />
<Icon.Chz size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cix size="40" color={random_hex_color_code()} variation="black" />
<Icon.Clam size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cloak size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cmm size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cmt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cnd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cnx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cny size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cob size="40" color={random_hex_color_code()} variation="black" />
<Icon.Colx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Comp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Coqui size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cred size="40" color={random_hex_color_code()} variation="black" />
<Icon.Crpt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Crv size="40" color={random_hex_color_code()} variation="black" />
<Icon.Crw size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cs size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ctr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ctxc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Cvc size="40" color={random_hex_color_code()} variation="black" />
<Icon.D size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dai size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dash size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dat size="40" color={random_hex_color_code()} variation="black" />
<Icon.Data size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dbc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dcn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dcr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Deez size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dent size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dew size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dgb size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dgd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dlt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dnt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dock size="40" color={random_hex_color_code()} variation="black" />
<Icon.Doge size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dot size="40" color={random_hex_color_code()} variation="black" />
<Icon.Drgn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Drop size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dta size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dth size="40" color={random_hex_color_code()} variation="black" />
<Icon.Dtr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ebst size="40" color={random_hex_color_code()} variation="black" />
<Icon.Eca size="40" color={random_hex_color_code()} variation="black" />
<Icon.Edg size="40" color={random_hex_color_code()} variation="black" />
<Icon.Edo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Edoge size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ela size="40" color={random_hex_color_code()} variation="black" />
<Icon.Elec size="40" color={random_hex_color_code()} variation="black" />
<Icon.Elf size="40" color={random_hex_color_code()} variation="black" />
<Icon.Elix size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ella size="40" color={random_hex_color_code()} variation="black" />
<Icon.Emb size="40" color={random_hex_color_code()} variation="black" />
<Icon.Emc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Emc2 size="40" color={random_hex_color_code()} variation="black" />
<Icon.Eng size="40" color={random_hex_color_code()} variation="black" />
<Icon.Enj size="40" color={random_hex_color_code()} variation="black" />
<Icon.Entrp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Eon size="40" color={random_hex_color_code()} variation="black" />
<Icon.Eop size="40" color={random_hex_color_code()} variation="black" />
<Icon.Eos size="40" color={random_hex_color_code()} variation="black" />
<Icon.Eqli size="40" color={random_hex_color_code()} variation="black" />
<Icon.Equa size="40" color={random_hex_color_code()} variation="black" />
<Icon.Etc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Eth size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ethos size="40" color={random_hex_color_code()} variation="black" />
<Icon.Etn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Etp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Eur size="40" color={random_hex_color_code()} variation="black" />
<Icon.Evx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Exmo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Exp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Fair size="40" color={random_hex_color_code()} variation="black" />
<Icon.Fct size="40" color={random_hex_color_code()} variation="black" />
<Icon.Fida size="40" color={random_hex_color_code()} variation="black" />
<Icon.Fil size="40" color={random_hex_color_code()} variation="black" />
<Icon.Fjc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Fldc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Flo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Flux size="40" color={random_hex_color_code()} variation="black" />
<Icon.Fsn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ftc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Fuel size="40" color={random_hex_color_code()} variation="black" />
<Icon.Fun size="40" color={random_hex_color_code()} variation="black" />
<Icon.Game size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gas size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gbp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gbx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gbyte size="40" color={random_hex_color_code()} variation="black" />
<Icon.Generic size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gin size="40" color={random_hex_color_code()} variation="black" />
<Icon.Glxt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gmr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gmt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gno size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gnt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gold size="40" color={random_hex_color_code()} variation="black" />
<Icon.Grc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Grin size="40" color={random_hex_color_code()} variation="black" />
<Icon.Grs size="40" color={random_hex_color_code()} variation="black" />
<Icon.Grt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gsc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gto size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gup size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gusd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gvt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gxs size="40" color={random_hex_color_code()} variation="black" />
<Icon.Gzr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Hight size="40" color={random_hex_color_code()} variation="black" />
<Icon.Hns size="40" color={random_hex_color_code()} variation="black" />
<Icon.Hodl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Hot size="40" color={random_hex_color_code()} variation="black" />
<Icon.Hpb size="40" color={random_hex_color_code()} variation="black" />
<Icon.Hsr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ht size="40" color={random_hex_color_code()} variation="black" />
<Icon.Html size="40" color={random_hex_color_code()} variation="black" />
<Icon.Huc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Husd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Hush size="40" color={random_hex_color_code()} variation="black" />
<Icon.Icn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Icp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Icx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ignis size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ilk size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ink size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ins size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ion size="40" color={random_hex_color_code()} variation="black" />
<Icon.Iop size="40" color={random_hex_color_code()} variation="black" />
<Icon.Iost size="40" color={random_hex_color_code()} variation="black" />
<Icon.Iotx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Iq size="40" color={random_hex_color_code()} variation="black" />
<Icon.Itc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Jnt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Jpy size="40" color={random_hex_color_code()} variation="black" />
<Icon.Kcs size="40" color={random_hex_color_code()} variation="black" />
<Icon.Kin size="40" color={random_hex_color_code()} variation="black" />
<Icon.Klown size="40" color={random_hex_color_code()} variation="black" />
<Icon.Kmd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Knc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Krb size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ksm size="40" color={random_hex_color_code()} variation="black" />
<Icon.Lbc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Lend size="40" color={random_hex_color_code()} variation="black" />
<Icon.Leo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Link size="40" color={random_hex_color_code()} variation="black" />
<Icon.Lkk size="40" color={random_hex_color_code()} variation="black" />
<Icon.Loom size="40" color={random_hex_color_code()} variation="black" />
<Icon.Lpt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Lrc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Lsk size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ltc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Lun size="40" color={random_hex_color_code()} variation="black" />
<Icon.Maid size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mana size="40" color={random_hex_color_code()} variation="black" />
<Icon.Matic size="40" color={random_hex_color_code()} variation="black" />
<Icon.Max size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mcap size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mco size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mda size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mds size="40" color={random_hex_color_code()} variation="black" />
<Icon.Med size="40" color={random_hex_color_code()} variation="black" />
<Icon.Meetone size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mft size="40" color={random_hex_color_code()} variation="black" />
<Icon.Miota size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mith size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mkr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mln size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mnx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mnz size="40" color={random_hex_color_code()} variation="black" />
<Icon.Moac size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mod size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mona size="40" color={random_hex_color_code()} variation="black" />
<Icon.Msr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mth size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mtl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Music size="40" color={random_hex_color_code()} variation="black" />
<Icon.Mzc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nano size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nas size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nav size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ncash size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ndz size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nebl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Neo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Neos size="40" color={random_hex_color_code()} variation="black" />
<Icon.Neu size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nexo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ngc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nio size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nkn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nlc2 size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nlg size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nmc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nmr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Npxs size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ntbc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nuls size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nxs size="40" color={random_hex_color_code()} variation="black" />
<Icon.Nxt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Oax size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ok size="40" color={random_hex_color_code()} variation="black" />
<Icon.Omg size="40" color={random_hex_color_code()} variation="black" />
<Icon.Omni size="40" color={random_hex_color_code()} variation="black" />
<Icon.One size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ong size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ont size="40" color={random_hex_color_code()} variation="black" />
<Icon.Oot size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ost size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ox size="40" color={random_hex_color_code()} variation="black" />
<Icon.Oxt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Oxy size="40" color={random_hex_color_code()} variation="black" />
<Icon.Part size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pasc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pasl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pax size="40" color={random_hex_color_code()} variation="black" />
<Icon.Paxg size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pay size="40" color={random_hex_color_code()} variation="black" />
<Icon.Payx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pink size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pirl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pivx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Plr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Poa size="40" color={random_hex_color_code()} variation="black" />
<Icon.Poe size="40" color={random_hex_color_code()} variation="black" />
<Icon.Polis size="40" color={random_hex_color_code()} variation="black" />
<Icon.Poly size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pot size="40" color={random_hex_color_code()} variation="black" />
<Icon.Powr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ppc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ppp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ppt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pre size="40" color={random_hex_color_code()} variation="black" />
<Icon.Prl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pungo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Pura size="40" color={random_hex_color_code()} variation="black" />
<Icon.Qash size="40" color={random_hex_color_code()} variation="black" />
<Icon.Qiwi size="40" color={random_hex_color_code()} variation="black" />
<Icon.Qlc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Qnt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Qrl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Qsp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Qtum size="40" color={random_hex_color_code()} variation="black" />
<Icon.R size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rads size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rap size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ray size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rcn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rdd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rdn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ren size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rep size="40" color={random_hex_color_code()} variation="black" />
<Icon.Repv2 size="40" color={random_hex_color_code()} variation="black" />
<Icon.Req size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rhoc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ric size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rise size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rlc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rpx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rub size="40" color={random_hex_color_code()} variation="black" />
<Icon.Rvn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ryo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Safe size="40" color={random_hex_color_code()} variation="black" />
<Icon.Safemoon size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sai size="40" color={random_hex_color_code()} variation="black" />
<Icon.Salt size="40" color={random_hex_color_code()} variation="black" />
<Icon.San size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sand size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sbd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sberbank size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ser size="40" color={random_hex_color_code()} variation="black" />
<Icon.Shift size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sib size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sin size="40" color={random_hex_color_code()} variation="black" />
<Icon.Skl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sky size="40" color={random_hex_color_code()} variation="black" />
<Icon.Slr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sls size="40" color={random_hex_color_code()} variation="black" />
<Icon.Smart size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sngls size="40" color={random_hex_color_code()} variation="black" />
<Icon.Snm size="40" color={random_hex_color_code()} variation="black" />
<Icon.Snt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Snx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Soc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sol size="40" color={random_hex_color_code()} variation="black" />
<Icon.Spacehbit size="40" color={random_hex_color_code()} variation="black" />
<Icon.Spank size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sphtx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Srn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Stak size="40" color={random_hex_color_code()} variation="black" />
<Icon.Start size="40" color={random_hex_color_code()} variation="black" />
<Icon.Steem size="40" color={random_hex_color_code()} variation="black" />
<Icon.Storj size="40" color={random_hex_color_code()} variation="black" />
<Icon.Storm size="40" color={random_hex_color_code()} variation="black" />
<Icon.Stox size="40" color={random_hex_color_code()} variation="black" />
<Icon.Stq size="40" color={random_hex_color_code()} variation="black" />
<Icon.Strat size="40" color={random_hex_color_code()} variation="black" />
<Icon.Stx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sub size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sumo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sushi size="40" color={random_hex_color_code()} variation="black" />
<Icon.Sys size="40" color={random_hex_color_code()} variation="black" />
<Icon.Taas size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tau size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tbx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tel size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ten size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tern size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tgch size="40" color={random_hex_color_code()} variation="black" />
<Icon.Theta size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tix size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tkn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tks size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tnb size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tnc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tnt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tomo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tpay size="40" color={random_hex_color_code()} variation="black" />
<Icon.Trig size="40" color={random_hex_color_code()} variation="black" />
<Icon.Trtl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Trx size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tusd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Tzc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Ubq size="40" color={random_hex_color_code()} variation="black" />
<Icon.Uma size="40" color={random_hex_color_code()} variation="black" />
<Icon.Uni size="40" color={random_hex_color_code()} variation="black" />
<Icon.Unity size="40" color={random_hex_color_code()} variation="black" />
<Icon.Usd size="40" color={random_hex_color_code()} variation="black" />
<Icon.Usdc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Usdt size="40" color={random_hex_color_code()} variation="black" />
<Icon.Utk size="40" color={random_hex_color_code()} variation="black" />
<Icon.Veri size="40" color={random_hex_color_code()} variation="black" />
<Icon.Vet size="40" color={random_hex_color_code()} variation="black" />
<Icon.Via size="40" color={random_hex_color_code()} variation="black" />
<Icon.Vib size="40" color={random_hex_color_code()} variation="black" />
<Icon.Vibe size="40" color={random_hex_color_code()} variation="black" />
<Icon.Vivo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Vrc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Vrsc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Vtc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Vtho size="40" color={random_hex_color_code()} variation="black" />
<Icon.Wabi size="40" color={random_hex_color_code()} variation="black" />
<Icon.Wan size="40" color={random_hex_color_code()} variation="black" />
<Icon.Waves size="40" color={random_hex_color_code()} variation="black" />
<Icon.Wax size="40" color={random_hex_color_code()} variation="black" />
<Icon.Wbtc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Wgr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Wicc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Wings size="40" color={random_hex_color_code()} variation="black" />
<Icon.Wpr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Wtc size="40" color={random_hex_color_code()} variation="black" />
<Icon.X size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xas size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xbc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xbp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xby size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xcp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xdn size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xem size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xin size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xlm size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xmcc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xmg size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xmo size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xmr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xmy size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xpa size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xpm size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xpr size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xrp size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xsg size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xtz size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xuc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xvc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xvg size="40" color={random_hex_color_code()} variation="black" />
<Icon.Xzc size="40" color={random_hex_color_code()} variation="black" />
<Icon.Yfi size="40" color={random_hex_color_code()} variation="black" />
<Icon.Yoyow size="40" color={random_hex_color_code()} variation="black" />
<Icon.Zcl size="40" color={random_hex_color_code()} variation="black" />
<Icon.Zec size="40" color={random_hex_color_code()} variation="black" />
<Icon.Zel size="40" color={random_hex_color_code()} variation="black" />
<Icon.Zen size="40" color={random_hex_color_code()} variation="black" />
<Icon.Zest size="40" color={random_hex_color_code()} variation="black" />
<Icon.Zil size="40" color={random_hex_color_code()} variation="black" />
<Icon.Zilla size="40" color={random_hex_color_code()} variation="black" />
<Icon.Zrx size="40" color={random_hex_color_code()} variation="black" />
